#!/bin/bash
# ComfyUI Complete Setup Script for RunPod
# This script performs all setup stages from the design document

set -e

echo "========================================="
echo "ComfyUI Setup - Starting"
echo "========================================="

# Store all actions for report
ACTIONS_LOG="/tmp/setup_actions.log"
echo "ComfyUI Setup Actions - $(date)" > "$ACTIONS_LOG"

# Stage 1: Environment Validation
echo "[Stage 1] Environment Validation" | tee -a "$ACTIONS_LOG"
cd /workspace/ComfyUI
source venv/bin/activate

echo "Python version:" | tee -a "$ACTIONS_LOG"
python --version | tee -a "$ACTIONS_LOG"

echo "GPU Check:" | tee -a "$ACTIONS_LOG"
python - << 'EOF' | tee -a "$ACTIONS_LOG"
import torch
print(f"CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Device: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version: {torch.version.cuda}")
else:
    print("WARNING: CUDA not available!")
    exit(1)
EOF

# Stage 2: Create Model Directory Structure
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 2] Creating Model Directory Structure" | tee -a "$ACTIONS_LOG"
mkdir -p /workspace/ComfyUI/models/checkpoints
mkdir -p /workspace/ComfyUI/models/controlnet
mkdir -p /workspace/ComfyUI/models/loras
mkdir -p /workspace/ComfyUI/models/ipadapter
mkdir -p /workspace/ComfyUI/models/vae
mkdir -p /workspace/ComfyUI/models/clip
echo "✓ Model directories created" | tee -a "$ACTIONS_LOG"

# Stage 3: Install Core Dependencies
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 3] Installing Core Dependencies" | tee -a "$ACTIONS_LOG"
pip install -r requirements.txt --quiet 2>&1 | grep -v "already satisfied" | tee -a "$ACTIONS_LOG" || true
pip install tqdm --quiet 2>&1 | tee -a "$ACTIONS_LOG"
pip install safetensors --quiet 2>&1 | tee -a "$ACTIONS_LOG"
pip install pillow==10.3.0 --quiet 2>&1 | tee -a "$ACTIONS_LOG"
echo "✓ Dependencies installed" | tee -a "$ACTIONS_LOG"

# Stage 4: Install Custom Nodes
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 4] Installing Custom Node Extensions" | tee -a "$ACTIONS_LOG"
cd /workspace/ComfyUI/custom_nodes

# ComfyUI-Manager
if [ ! -d "ComfyUI-Manager" ]; then
    echo "Installing ComfyUI-Manager..." | tee -a "$ACTIONS_LOG"
    git clone https://github.com/ltdrdata/ComfyUI-Manager.git 2>&1 | tee -a "$ACTIONS_LOG"
else
    echo "ComfyUI-Manager already installed" | tee -a "$ACTIONS_LOG"
fi

# ControlNet Aux
if [ ! -d "comfyui_controlnet_aux" ]; then
    echo "Installing ControlNet Aux..." | tee -a "$ACTIONS_LOG"
    git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git 2>&1 | tee -a "$ACTIONS_LOG"
else
    echo "ControlNet Aux already installed" | tee -a "$ACTIONS_LOG"
fi

# WAS Node Suite
if [ ! -d "was-node-suite-comfyui" ]; then
    echo "Installing WAS Node Suite..." | tee -a "$ACTIONS_LOG"
    git clone https://github.com/WASasquatch/was-node-suite-comfyui.git 2>&1 | tee -a "$ACTIONS_LOG"
else
    echo "WAS Node Suite already installed" | tee -a "$ACTIONS_LOG"
fi

# IPAdapter Plus
if [ ! -d "ComfyUI_IPAdapter_plus" ]; then
    echo "Installing IPAdapter Plus..." | tee -a "$ACTIONS_LOG"
    git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus.git 2>&1 | tee -a "$ACTIONS_LOG"
else
    echo "IPAdapter Plus already installed" | tee -a "$ACTIONS_LOG"
fi

# Custom Scripts
if [ ! -d "ComfyUI-Custom-Scripts" ]; then
    echo "Installing Custom Scripts..." | tee -a "$ACTIONS_LOG"
    git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git 2>&1 | tee -a "$ACTIONS_LOG"
else
    echo "Custom Scripts already installed" | tee -a "$ACTIONS_LOG"
fi

echo "✓ Custom nodes installed" | tee -a "$ACTIONS_LOG"

# Stage 5: Performance Optimization Configuration
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 5] Applying Performance Optimization" | tee -a "$ACTIONS_LOG"
cd /workspace/ComfyUI

cat > extra_model_paths.yaml << 'YAML_EOF'
# Performance optimizations for large models
# Generated by setup script
YAML_EOF

# Create config file if it doesn't exist
if [ ! -f "config.json" ]; then
    cat > config.json << 'JSON_EOF'
{
  "fast_load": true,
  "cache_weights": true,
  "tiled_vae": true,
  "vram_optimizations": "normal",
  "load_half": true
}
JSON_EOF
    echo "✓ Performance config created" | tee -a "$ACTIONS_LOG"
else
    echo "Config file already exists, skipping" | tee -a "$ACTIONS_LOG"
fi

# Stage 6: Restart Service
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 6] Restarting ComfyUI Service" | tee -a "$ACTIONS_LOG"

# Kill existing processes
pkill -f "python main.py" || true
sleep 2

# Start using the existing startup script
bash /workspace/.runpod/scripts/start.sh &
sleep 5

echo "✓ Service restarted" | tee -a "$ACTIONS_LOG"

# Stage 7: Verification
echo "" | tee -a "$ACTIONS_LOG"
echo "[Stage 7] Verification" | tee -a "$ACTIONS_LOG"

# Check if process is running
if ps aux | grep -v grep | grep "python main.py" > /dev/null; then
    echo "✓ ComfyUI process is running" | tee -a "$ACTIONS_LOG"
else
    echo "✗ ComfyUI process NOT running" | tee -a "$ACTIONS_LOG"
fi

# Check logs
echo "" | tee -a "$ACTIONS_LOG"
echo "Last 50 lines of ComfyUI log:" | tee -a "$ACTIONS_LOG"
if [ -f "/workspace/.runpod/logs/comfyui.log" ]; then
    tail -n 50 /workspace/.runpod/logs/comfyui.log | tee -a "$ACTIONS_LOG"
else
    echo "Log file not found!" | tee -a "$ACTIONS_LOG"
fi

# Generate Final Report
echo "" | tee -a "$ACTIONS_LOG"
echo "=========================================" | tee -a "$ACTIONS_LOG"
echo "FINAL REPORT" | tee -a "$ACTIONS_LOG"
echo "=========================================" | tee -a "$ACTIONS_LOG"

echo "" | tee -a "$ACTIONS_LOG"
echo "=== Installed Python Packages ===" | tee -a "$ACTIONS_LOG"
pip list | tee -a "$ACTIONS_LOG"

echo "" | tee -a "$ACTIONS_LOG"
echo "=== Custom Nodes ===" | tee -a "$ACTIONS_LOG"
ls -la /workspace/ComfyUI/custom_nodes/ | tee -a "$ACTIONS_LOG"

echo "" | tee -a "$ACTIONS_LOG"
echo "=== Model Directory Structure ===" | tee -a "$ACTIONS_LOG"
tree -L 2 /workspace/ComfyUI/models/ || ls -la /workspace/ComfyUI/models/

echo "" | tee -a "$ACTIONS_LOG"
echo "=========================================" | tee -a "$ACTIONS_LOG"
echo "Setup Complete!" | tee -a "$ACTIONS_LOG"
echo "=========================================" | tee -a "$ACTIONS_LOG"

# Copy log to workspace for easy access
cp "$ACTIONS_LOG" /workspace/.runpod/logs/setup_report.log
echo "Full report saved to: /workspace/.runpod/logs/setup_report.log"
